apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: cni-bash
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cni-bash
subjects:
- kind: ServiceAccount
  name: cni-bash
  namespace: cni-bash-system
